<!-- JS here -->
<script src="{{ asset('dist-front/js/vendor/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('dist-front/js/vendor/waypoints.min.js') }}"></script>
<script src="{{ asset('dist-front/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery.meanmenu.js') }}"></script>
<script src="{{ asset('dist-front/js/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('dist-front/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery.fancybox.min.js') }}"></script>
<script src="{{ asset('dist-front/js/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('dist-front/js/parallax.min.js') }}"></script>
<script src="{{ asset('dist-front/js/backToTop.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery.counterup.min.js') }}"></script>
<script src="{{ asset('dist-front/js/ajax-form.js') }}"></script>
<script src="{{ asset('dist-front/js/wow.min.js') }}"></script>
<script src="{{ asset('dist-front/js/imagesloaded.pkgd.min.js') }}"></script>
<script src="{{ asset('dist-front/js/wavify.js') }}"></script>
<script src="{{ asset('dist-front/js/main.js') }}"></script>
